### ISSUE TITLE
Refetch youtube title issue

### ISSUE THREAD

**Issue by profcaju** [joshp23/YOURLS-title-refetch#11]
I use yourls to create short urls for my youtube channel.

80% of the times I add a short url form my youtube channel, the title in yourls admin page shows just "Youtube". That's why I added this plugin.

But, when clicking the refetch button in admin page, I have to click several times (sometimes even 30 times) to fetch the title from youtube. Is this some timeout issue, or something known?

Kind regards,

**Comment by joshp23** [comment]
I can confirm the same behavior, but have no idea why, other than... YouTube is gonna YouTube. It might be worth while to consider writing a plugin that uses the google api to fetch YouTube data...

**Comment by joshp23** [comment]
I just published a new plugin to address this issue. [Enjoy](https://github.com/joshp23/YOURLS-YouTube-title-fix)
